---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - app/**.rb
  - lib/**.rb
exclude_paths:
- spec/
