---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
    - app/**
    - config/**
    - features/**
    - lib/**
    - spec/**
exclude_paths:
  - config/
  - db/
  - spec/
  - vendor/
