---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
exclude_paths:
  - config/
  - db/
  - spec/
  - vendor/
