Documentation:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/BlockComments:
  Enabled: false

Metrics/LineLength:
  Max: 120
