Documentation:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'script/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/BlockComments:
  Enabled: false

Metrics/LineLength:
  Max: 120

# %w[] shows that it will return an array
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
